
[package]
name = "diff_doc"
version = "0.4.0"
edition = "2024"


[dependencies]
#diffs = "0.5"

# plain text diff
diffy="0.4"

# yaml diff nothing

serde_json = { version = "1.0", features = ["arbitrary_precision"] }
#thiserror = "1.0.69"

serde = { version = "1.0", features = ["derive", "serde_derive", "std"] }
serde-xml-rs = "*"


serde_yaml = "0.9"
toml = "0.8"
rand = "0.9.2"
diff = "0.1.13"
ahash = "0.8.12"

[dev-dependencies]
uuid = { version = "1.10", features = ["v4"] }

