
[package]
name = "diff_doc"
version = "0.4.0"
edition = "2024"


[dependencies]
#diffs = "0.5"

# plain text diff
diffy="0.4"

# yaml diff nothing

serde_json = "1.0.140"
#thiserror = "1.0.69"

serde = { version = "1.0", features = ["serde_derive", "std"] }
serde-xml-rs = "*"

