/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: diff.proto */

#ifndef PROTOBUF_C_diff_2eproto__INCLUDED
#define PROTOBUF_C_diff_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct DiffDoc__Mismatches DiffDoc__Mismatches;
typedef struct DiffDoc__DocMismatch DiffDoc__DocMismatch;
typedef struct DiffDoc__Hunk DiffDoc__Hunk;
typedef struct DiffDoc__DocIndex DiffDoc__DocIndex;
typedef struct DiffDoc__HunkAction DiffDoc__HunkAction;
typedef struct DiffDoc__GenericValue DiffDoc__GenericValue;
typedef struct DiffDoc__GenericMap DiffDoc__GenericMap;
typedef struct DiffDoc__GenericMap__FieldsEntry DiffDoc__GenericMap__FieldsEntry;
typedef struct DiffDoc__GenericArray DiffDoc__GenericArray;
typedef struct DiffDoc__TxtMismatch DiffDoc__TxtMismatch;
typedef struct DiffDoc__DiffOp DiffDoc__DiffOp;
typedef struct DiffDoc__DiffOpRemove DiffDoc__DiffOpRemove;
typedef struct DiffDoc__DiffOpInsert DiffDoc__DiffOpInsert;
typedef struct DiffDoc__DiffOpUpdate DiffDoc__DiffOpUpdate;
typedef struct DiffDoc__DiffOpAppend DiffDoc__DiffOpAppend;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  DIFF_DOC__MISMATCHES__KIND__NOT_SET = 0,
  DIFF_DOC__MISMATCHES__KIND_PATCH = 1,
  DIFF_DOC__MISMATCHES__KIND_DOC = 2,
  DIFF_DOC__MISMATCHES__KIND_TEXT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIFF_DOC__MISMATCHES__KIND__CASE)
} DiffDoc__Mismatches__KindCase;

/*
 * Corresponds to enum Mismatches in src/lib.rs
 */
struct  DiffDoc__Mismatches
{
  ProtobufCMessage base;
  DiffDoc__Mismatches__KindCase kind_case;
  union {
    /*
     * patch::Mismatch (feature = "patch") — raw GNU patch text
     */
    char *patch;
    /*
     * diff::Mismatch  — structured JSON/document diff
     */
    DiffDoc__DocMismatch *doc;
    /*
     * txt::Mismatch   — line-level text diff
     */
    DiffDoc__TxtMismatch *text;
  };
};
#define DIFF_DOC__MISMATCHES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__mismatches__descriptor) \
    , DIFF_DOC__MISMATCHES__KIND__NOT_SET, {0} }


/*
 * Corresponds to diff::Mismatch(Vec<Hunk>) in src/diff.rs
 */
struct  DiffDoc__DocMismatch
{
  ProtobufCMessage base;
  size_t n_hunks;
  DiffDoc__Hunk **hunks;
};
#define DIFF_DOC__DOC_MISMATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__doc_mismatch__descriptor) \
    , 0,NULL }


/*
 * Corresponds to generic::Hunk in src/generic.rs
 * serde renames: path → "p", value → "v"
 */
struct  DiffDoc__Hunk
{
  ProtobufCMessage base;
  /*
   * "p"
   */
  size_t n_path;
  DiffDoc__DocIndex **path;
  /*
   * "v"
   */
  DiffDoc__HunkAction *value;
};
#define DIFF_DOC__HUNK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__hunk__descriptor) \
    , 0,NULL, NULL }


typedef enum {
  DIFF_DOC__DOC_INDEX__KIND__NOT_SET = 0,
  DIFF_DOC__DOC_INDEX__KIND_NAME = 1,
  DIFF_DOC__DOC_INDEX__KIND_IDX = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIFF_DOC__DOC_INDEX__KIND__CASE)
} DiffDoc__DocIndex__KindCase;

/*
 * Corresponds to generic::DocIndex in src/generic.rs
 * serde renames: Name → "n", Idx → "i"
 */
struct  DiffDoc__DocIndex
{
  ProtobufCMessage base;
  DiffDoc__DocIndex__KindCase kind_case;
  union {
    /*
     * "n"
     */
    char *name;
    /*
     * "i"
     */
    uint64_t idx;
  };
};
#define DIFF_DOC__DOC_INDEX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__doc_index__descriptor) \
    , DIFF_DOC__DOC_INDEX__KIND__NOT_SET, {0} }


typedef enum {
  DIFF_DOC__HUNK_ACTION__KIND__NOT_SET = 0,
  DIFF_DOC__HUNK_ACTION__KIND_REMOVE = 1,
  DIFF_DOC__HUNK_ACTION__KIND_UPDATE = 2,
  DIFF_DOC__HUNK_ACTION__KIND_UPDATE_TXT = 3,
  DIFF_DOC__HUNK_ACTION__KIND_INSERT = 4,
  DIFF_DOC__HUNK_ACTION__KIND_SWAP = 5,
  DIFF_DOC__HUNK_ACTION__KIND_CLONE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIFF_DOC__HUNK_ACTION__KIND__CASE)
} DiffDoc__HunkAction__KindCase;

/*
 * Corresponds to generic::HunkAction in src/generic.rs
 */
struct  DiffDoc__HunkAction
{
  ProtobufCMessage base;
  DiffDoc__HunkAction__KindCase kind_case;
  union {
    /*
     * Remove (unit variant — set true)
     */
    protobuf_c_boolean remove;
    /*
     * Update(GenericValue)
     */
    DiffDoc__GenericValue *update;
    /*
     * UpdateTxt(Vec<DiffOp>)
     */
    DiffDoc__TxtMismatch *update_txt;
    /*
     * Insert(GenericValue)
     */
    DiffDoc__GenericValue *insert;
    /*
     * Swap(DocIndex)
     */
    DiffDoc__DocIndex *swap;
    /*
     * Clone(DocIndex)
     */
    DiffDoc__DocIndex *clone;
  };
};
#define DIFF_DOC__HUNK_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__hunk_action__descriptor) \
    , DIFF_DOC__HUNK_ACTION__KIND__NOT_SET, {0} }


typedef enum {
  DIFF_DOC__GENERIC_VALUE__KIND__NOT_SET = 0,
  DIFF_DOC__GENERIC_VALUE__KIND_NUMERIC = 1,
  DIFF_DOC__GENERIC_VALUE__KIND_MAP = 2,
  DIFF_DOC__GENERIC_VALUE__KIND_ARRAY = 3,
  DIFF_DOC__GENERIC_VALUE__KIND_BOOLEAN = 4,
  DIFF_DOC__GENERIC_VALUE__KIND_STRING = 5,
  DIFF_DOC__GENERIC_VALUE__KIND_NULL = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIFF_DOC__GENERIC_VALUE__KIND__CASE)
} DiffDoc__GenericValue__KindCase;

/*
 * Corresponds to generic::GenericValue in src/generic.rs (untagged serde)
 */
struct  DiffDoc__GenericValue
{
  ProtobufCMessage base;
  DiffDoc__GenericValue__KindCase kind_case;
  union {
    /*
     * Numeric(NumericString) — number stored as string
     */
    char *numeric;
    /*
     * Map(HashMap<String, GenericValue>)
     */
    DiffDoc__GenericMap *map;
    /*
     * Array(Vec<GenericValue>)
     */
    DiffDoc__GenericArray *array;
    /*
     * Boolean(bool)
     */
    protobuf_c_boolean boolean;
    /*
     * StringValue(String)
     */
    char *string;
    /*
     * Null (set true)
     */
    protobuf_c_boolean null;
  };
};
#define DIFF_DOC__GENERIC_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__generic_value__descriptor) \
    , DIFF_DOC__GENERIC_VALUE__KIND__NOT_SET, {0} }


struct  DiffDoc__GenericMap__FieldsEntry
{
  ProtobufCMessage base;
  char *key;
  DiffDoc__GenericValue *value;
};
#define DIFF_DOC__GENERIC_MAP__FIELDS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__generic_map__fields_entry__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  DiffDoc__GenericMap
{
  ProtobufCMessage base;
  size_t n_fields;
  DiffDoc__GenericMap__FieldsEntry **fields;
};
#define DIFF_DOC__GENERIC_MAP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__generic_map__descriptor) \
    , 0,NULL }


struct  DiffDoc__GenericArray
{
  ProtobufCMessage base;
  size_t n_items;
  DiffDoc__GenericValue **items;
};
#define DIFF_DOC__GENERIC_ARRAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__generic_array__descriptor) \
    , 0,NULL }


/*
 * Corresponds to txt::Mismatch(Vec<DiffOp>) in src/txt.rs
 */
struct  DiffDoc__TxtMismatch
{
  ProtobufCMessage base;
  size_t n_ops;
  DiffDoc__DiffOp **ops;
};
#define DIFF_DOC__TXT_MISMATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__txt_mismatch__descriptor) \
    , 0,NULL }


typedef enum {
  DIFF_DOC__DIFF_OP__KIND__NOT_SET = 0,
  DIFF_DOC__DIFF_OP__KIND_REMOVE = 1,
  DIFF_DOC__DIFF_OP__KIND_INSERT = 2,
  DIFF_DOC__DIFF_OP__KIND_UPDATE = 3,
  DIFF_DOC__DIFF_OP__KIND_APPEND = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIFF_DOC__DIFF_OP__KIND__CASE)
} DiffDoc__DiffOp__KindCase;

/*
 * Corresponds to txt::DiffOp in src/txt.rs
 */
struct  DiffDoc__DiffOp
{
  ProtobufCMessage base;
  DiffDoc__DiffOp__KindCase kind_case;
  union {
    /*
     * Remove { index }
     */
    DiffDoc__DiffOpRemove *remove;
    /*
     * Insert { index, value }
     */
    DiffDoc__DiffOpInsert *insert;
    /*
     * Update { index, value }
     */
    DiffDoc__DiffOpUpdate *update;
    /*
     * Append { index, pos, value }
     */
    DiffDoc__DiffOpAppend *append;
  };
};
#define DIFF_DOC__DIFF_OP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__diff_op__descriptor) \
    , DIFF_DOC__DIFF_OP__KIND__NOT_SET, {0} }


struct  DiffDoc__DiffOpRemove
{
  ProtobufCMessage base;
  uint64_t index;
};
#define DIFF_DOC__DIFF_OP_REMOVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__diff_op_remove__descriptor) \
    , 0 }


struct  DiffDoc__DiffOpInsert
{
  ProtobufCMessage base;
  uint64_t index;
  char *value;
};
#define DIFF_DOC__DIFF_OP_INSERT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__diff_op_insert__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  DiffDoc__DiffOpUpdate
{
  ProtobufCMessage base;
  uint64_t index;
  char *value;
};
#define DIFF_DOC__DIFF_OP_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__diff_op_update__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  DiffDoc__DiffOpAppend
{
  ProtobufCMessage base;
  uint64_t index;
  uint64_t pos;
  char *value;
};
#define DIFF_DOC__DIFF_OP_APPEND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff_doc__diff_op_append__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string }


/* DiffDoc__Mismatches methods */
void   diff_doc__mismatches__init
                     (DiffDoc__Mismatches         *message);
size_t diff_doc__mismatches__get_packed_size
                     (const DiffDoc__Mismatches   *message);
size_t diff_doc__mismatches__pack
                     (const DiffDoc__Mismatches   *message,
                      uint8_t             *out);
size_t diff_doc__mismatches__pack_to_buffer
                     (const DiffDoc__Mismatches   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__Mismatches *
       diff_doc__mismatches__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__mismatches__free_unpacked
                     (DiffDoc__Mismatches *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DocMismatch methods */
void   diff_doc__doc_mismatch__init
                     (DiffDoc__DocMismatch         *message);
size_t diff_doc__doc_mismatch__get_packed_size
                     (const DiffDoc__DocMismatch   *message);
size_t diff_doc__doc_mismatch__pack
                     (const DiffDoc__DocMismatch   *message,
                      uint8_t             *out);
size_t diff_doc__doc_mismatch__pack_to_buffer
                     (const DiffDoc__DocMismatch   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DocMismatch *
       diff_doc__doc_mismatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__doc_mismatch__free_unpacked
                     (DiffDoc__DocMismatch *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__Hunk methods */
void   diff_doc__hunk__init
                     (DiffDoc__Hunk         *message);
size_t diff_doc__hunk__get_packed_size
                     (const DiffDoc__Hunk   *message);
size_t diff_doc__hunk__pack
                     (const DiffDoc__Hunk   *message,
                      uint8_t             *out);
size_t diff_doc__hunk__pack_to_buffer
                     (const DiffDoc__Hunk   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__Hunk *
       diff_doc__hunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__hunk__free_unpacked
                     (DiffDoc__Hunk *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DocIndex methods */
void   diff_doc__doc_index__init
                     (DiffDoc__DocIndex         *message);
size_t diff_doc__doc_index__get_packed_size
                     (const DiffDoc__DocIndex   *message);
size_t diff_doc__doc_index__pack
                     (const DiffDoc__DocIndex   *message,
                      uint8_t             *out);
size_t diff_doc__doc_index__pack_to_buffer
                     (const DiffDoc__DocIndex   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DocIndex *
       diff_doc__doc_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__doc_index__free_unpacked
                     (DiffDoc__DocIndex *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__HunkAction methods */
void   diff_doc__hunk_action__init
                     (DiffDoc__HunkAction         *message);
size_t diff_doc__hunk_action__get_packed_size
                     (const DiffDoc__HunkAction   *message);
size_t diff_doc__hunk_action__pack
                     (const DiffDoc__HunkAction   *message,
                      uint8_t             *out);
size_t diff_doc__hunk_action__pack_to_buffer
                     (const DiffDoc__HunkAction   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__HunkAction *
       diff_doc__hunk_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__hunk_action__free_unpacked
                     (DiffDoc__HunkAction *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__GenericValue methods */
void   diff_doc__generic_value__init
                     (DiffDoc__GenericValue         *message);
size_t diff_doc__generic_value__get_packed_size
                     (const DiffDoc__GenericValue   *message);
size_t diff_doc__generic_value__pack
                     (const DiffDoc__GenericValue   *message,
                      uint8_t             *out);
size_t diff_doc__generic_value__pack_to_buffer
                     (const DiffDoc__GenericValue   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__GenericValue *
       diff_doc__generic_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__generic_value__free_unpacked
                     (DiffDoc__GenericValue *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__GenericMap__FieldsEntry methods */
void   diff_doc__generic_map__fields_entry__init
                     (DiffDoc__GenericMap__FieldsEntry         *message);
/* DiffDoc__GenericMap methods */
void   diff_doc__generic_map__init
                     (DiffDoc__GenericMap         *message);
size_t diff_doc__generic_map__get_packed_size
                     (const DiffDoc__GenericMap   *message);
size_t diff_doc__generic_map__pack
                     (const DiffDoc__GenericMap   *message,
                      uint8_t             *out);
size_t diff_doc__generic_map__pack_to_buffer
                     (const DiffDoc__GenericMap   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__GenericMap *
       diff_doc__generic_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__generic_map__free_unpacked
                     (DiffDoc__GenericMap *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__GenericArray methods */
void   diff_doc__generic_array__init
                     (DiffDoc__GenericArray         *message);
size_t diff_doc__generic_array__get_packed_size
                     (const DiffDoc__GenericArray   *message);
size_t diff_doc__generic_array__pack
                     (const DiffDoc__GenericArray   *message,
                      uint8_t             *out);
size_t diff_doc__generic_array__pack_to_buffer
                     (const DiffDoc__GenericArray   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__GenericArray *
       diff_doc__generic_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__generic_array__free_unpacked
                     (DiffDoc__GenericArray *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__TxtMismatch methods */
void   diff_doc__txt_mismatch__init
                     (DiffDoc__TxtMismatch         *message);
size_t diff_doc__txt_mismatch__get_packed_size
                     (const DiffDoc__TxtMismatch   *message);
size_t diff_doc__txt_mismatch__pack
                     (const DiffDoc__TxtMismatch   *message,
                      uint8_t             *out);
size_t diff_doc__txt_mismatch__pack_to_buffer
                     (const DiffDoc__TxtMismatch   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__TxtMismatch *
       diff_doc__txt_mismatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__txt_mismatch__free_unpacked
                     (DiffDoc__TxtMismatch *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DiffOp methods */
void   diff_doc__diff_op__init
                     (DiffDoc__DiffOp         *message);
size_t diff_doc__diff_op__get_packed_size
                     (const DiffDoc__DiffOp   *message);
size_t diff_doc__diff_op__pack
                     (const DiffDoc__DiffOp   *message,
                      uint8_t             *out);
size_t diff_doc__diff_op__pack_to_buffer
                     (const DiffDoc__DiffOp   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DiffOp *
       diff_doc__diff_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__diff_op__free_unpacked
                     (DiffDoc__DiffOp *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DiffOpRemove methods */
void   diff_doc__diff_op_remove__init
                     (DiffDoc__DiffOpRemove         *message);
size_t diff_doc__diff_op_remove__get_packed_size
                     (const DiffDoc__DiffOpRemove   *message);
size_t diff_doc__diff_op_remove__pack
                     (const DiffDoc__DiffOpRemove   *message,
                      uint8_t             *out);
size_t diff_doc__diff_op_remove__pack_to_buffer
                     (const DiffDoc__DiffOpRemove   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DiffOpRemove *
       diff_doc__diff_op_remove__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__diff_op_remove__free_unpacked
                     (DiffDoc__DiffOpRemove *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DiffOpInsert methods */
void   diff_doc__diff_op_insert__init
                     (DiffDoc__DiffOpInsert         *message);
size_t diff_doc__diff_op_insert__get_packed_size
                     (const DiffDoc__DiffOpInsert   *message);
size_t diff_doc__diff_op_insert__pack
                     (const DiffDoc__DiffOpInsert   *message,
                      uint8_t             *out);
size_t diff_doc__diff_op_insert__pack_to_buffer
                     (const DiffDoc__DiffOpInsert   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DiffOpInsert *
       diff_doc__diff_op_insert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__diff_op_insert__free_unpacked
                     (DiffDoc__DiffOpInsert *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DiffOpUpdate methods */
void   diff_doc__diff_op_update__init
                     (DiffDoc__DiffOpUpdate         *message);
size_t diff_doc__diff_op_update__get_packed_size
                     (const DiffDoc__DiffOpUpdate   *message);
size_t diff_doc__diff_op_update__pack
                     (const DiffDoc__DiffOpUpdate   *message,
                      uint8_t             *out);
size_t diff_doc__diff_op_update__pack_to_buffer
                     (const DiffDoc__DiffOpUpdate   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DiffOpUpdate *
       diff_doc__diff_op_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__diff_op_update__free_unpacked
                     (DiffDoc__DiffOpUpdate *message,
                      ProtobufCAllocator *allocator);
/* DiffDoc__DiffOpAppend methods */
void   diff_doc__diff_op_append__init
                     (DiffDoc__DiffOpAppend         *message);
size_t diff_doc__diff_op_append__get_packed_size
                     (const DiffDoc__DiffOpAppend   *message);
size_t diff_doc__diff_op_append__pack
                     (const DiffDoc__DiffOpAppend   *message,
                      uint8_t             *out);
size_t diff_doc__diff_op_append__pack_to_buffer
                     (const DiffDoc__DiffOpAppend   *message,
                      ProtobufCBuffer     *buffer);
DiffDoc__DiffOpAppend *
       diff_doc__diff_op_append__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff_doc__diff_op_append__free_unpacked
                     (DiffDoc__DiffOpAppend *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DiffDoc__Mismatches_Closure)
                 (const DiffDoc__Mismatches *message,
                  void *closure_data);
typedef void (*DiffDoc__DocMismatch_Closure)
                 (const DiffDoc__DocMismatch *message,
                  void *closure_data);
typedef void (*DiffDoc__Hunk_Closure)
                 (const DiffDoc__Hunk *message,
                  void *closure_data);
typedef void (*DiffDoc__DocIndex_Closure)
                 (const DiffDoc__DocIndex *message,
                  void *closure_data);
typedef void (*DiffDoc__HunkAction_Closure)
                 (const DiffDoc__HunkAction *message,
                  void *closure_data);
typedef void (*DiffDoc__GenericValue_Closure)
                 (const DiffDoc__GenericValue *message,
                  void *closure_data);
typedef void (*DiffDoc__GenericMap__FieldsEntry_Closure)
                 (const DiffDoc__GenericMap__FieldsEntry *message,
                  void *closure_data);
typedef void (*DiffDoc__GenericMap_Closure)
                 (const DiffDoc__GenericMap *message,
                  void *closure_data);
typedef void (*DiffDoc__GenericArray_Closure)
                 (const DiffDoc__GenericArray *message,
                  void *closure_data);
typedef void (*DiffDoc__TxtMismatch_Closure)
                 (const DiffDoc__TxtMismatch *message,
                  void *closure_data);
typedef void (*DiffDoc__DiffOp_Closure)
                 (const DiffDoc__DiffOp *message,
                  void *closure_data);
typedef void (*DiffDoc__DiffOpRemove_Closure)
                 (const DiffDoc__DiffOpRemove *message,
                  void *closure_data);
typedef void (*DiffDoc__DiffOpInsert_Closure)
                 (const DiffDoc__DiffOpInsert *message,
                  void *closure_data);
typedef void (*DiffDoc__DiffOpUpdate_Closure)
                 (const DiffDoc__DiffOpUpdate *message,
                  void *closure_data);
typedef void (*DiffDoc__DiffOpAppend_Closure)
                 (const DiffDoc__DiffOpAppend *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor diff_doc__mismatches__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__doc_mismatch__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__hunk__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__doc_index__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__hunk_action__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__generic_value__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__generic_map__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__generic_map__fields_entry__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__generic_array__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__txt_mismatch__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__diff_op__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__diff_op_remove__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__diff_op_insert__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__diff_op_update__descriptor;
extern const ProtobufCMessageDescriptor diff_doc__diff_op_append__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_diff_2eproto__INCLUDED */
