#ifndef DIFF_APPLY_H
#define DIFF_APPLY_H

#include <stddef.h>
#include <stdint.h>

/* Generated by protoc-c from proto/mismatches.proto */
#include "mismatches.pb-c.h"

/* ── GenericValue: the live document tree being patched ─────────────── */

typedef enum {
    GV_NULL,
    GV_BOOL,
    GV_NUMERIC,   /* number stored as NUL-terminated string (arbitrary precision) */
    GV_STRING,
    GV_ARRAY,
    GV_MAP,
} GvKind;

typedef struct GenericValue GenericValue;

typedef struct {
    char         *key;
    GenericValue *val;
} MapEntry;

struct GenericValue {
    GvKind kind;
    union {
        int      boolean;   /* GV_BOOL */
        char    *string;    /* GV_STRING, GV_NUMERIC */
        struct {
            GenericValue **items;
            size_t         len;
            size_t         cap;
        } arr;              /* GV_ARRAY */
        struct {
            MapEntry *ents;
            size_t    len;
            size_t    cap;
        } map;              /* GV_MAP */
    };
};

/* ── Error ──────────────────────────────────────────────────────────── */

typedef struct {
    char *msg;   /* heap-allocated; NULL means no error */
} DocError;

/* ── API ────────────────────────────────────────────────────────────── */

/*
 * CoW apply: clones `doc`, applies the diff, returns the new value.
 * On error returns NULL and writes a message into *out_err.
 * Caller must gv_free() the result and doc_error_free() on error.
 */
GenericValue *mismatches_apply(const DiffDoc__Mismatches *diff,
                               const GenericValue        *doc,
                               DocError                  *out_err);

/*
 * In-place apply: modifies `doc` directly.
 *
 * fail_fast != 0  → stop at the first error; returns -1, with errs[0] set.
 * fail_fast == 0  → apply all hunks, collect soft errors into errs[].
 *                   Returns the number of errors written (0 = full success).
 *
 * NOTE: partial application is possible on both paths (non-transactional,
 *       mirroring the Rust MismatchDocMut contract).
 */
int mismatches_apply_mut(const DiffDoc__Mismatches *diff,
                         GenericValue              *doc,
                         int                        fail_fast,
                         DocError                  *errs,
                         size_t                     errs_cap,
                         size_t                    *errs_len_out);

/* ── Memory ─────────────────────────────────────────────────────────── */

GenericValue *gv_clone(const GenericValue *src);
void          gv_free (GenericValue *gv);
void          doc_error_free(DocError *e);

#endif /* DIFF_APPLY_H */
