/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: diff.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "diff.pb-c.h"
void   diff_doc__mismatches__init
                     (DiffDoc__Mismatches         *message)
{
  static const DiffDoc__Mismatches init_value = DIFF_DOC__MISMATCHES__INIT;
  *message = init_value;
}
size_t diff_doc__mismatches__get_packed_size
                     (const DiffDoc__Mismatches *message)
{
  assert(message->base.descriptor == &diff_doc__mismatches__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__mismatches__pack
                     (const DiffDoc__Mismatches *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__mismatches__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__mismatches__pack_to_buffer
                     (const DiffDoc__Mismatches *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__mismatches__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__Mismatches *
       diff_doc__mismatches__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__Mismatches *)
     protobuf_c_message_unpack (&diff_doc__mismatches__descriptor,
                                allocator, len, data);
}
void   diff_doc__mismatches__free_unpacked
                     (DiffDoc__Mismatches *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__mismatches__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__doc_mismatch__init
                     (DiffDoc__DocMismatch         *message)
{
  static const DiffDoc__DocMismatch init_value = DIFF_DOC__DOC_MISMATCH__INIT;
  *message = init_value;
}
size_t diff_doc__doc_mismatch__get_packed_size
                     (const DiffDoc__DocMismatch *message)
{
  assert(message->base.descriptor == &diff_doc__doc_mismatch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__doc_mismatch__pack
                     (const DiffDoc__DocMismatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__doc_mismatch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__doc_mismatch__pack_to_buffer
                     (const DiffDoc__DocMismatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__doc_mismatch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DocMismatch *
       diff_doc__doc_mismatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DocMismatch *)
     protobuf_c_message_unpack (&diff_doc__doc_mismatch__descriptor,
                                allocator, len, data);
}
void   diff_doc__doc_mismatch__free_unpacked
                     (DiffDoc__DocMismatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__doc_mismatch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__hunk__init
                     (DiffDoc__Hunk         *message)
{
  static const DiffDoc__Hunk init_value = DIFF_DOC__HUNK__INIT;
  *message = init_value;
}
size_t diff_doc__hunk__get_packed_size
                     (const DiffDoc__Hunk *message)
{
  assert(message->base.descriptor == &diff_doc__hunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__hunk__pack
                     (const DiffDoc__Hunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__hunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__hunk__pack_to_buffer
                     (const DiffDoc__Hunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__hunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__Hunk *
       diff_doc__hunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__Hunk *)
     protobuf_c_message_unpack (&diff_doc__hunk__descriptor,
                                allocator, len, data);
}
void   diff_doc__hunk__free_unpacked
                     (DiffDoc__Hunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__hunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__doc_index__init
                     (DiffDoc__DocIndex         *message)
{
  static const DiffDoc__DocIndex init_value = DIFF_DOC__DOC_INDEX__INIT;
  *message = init_value;
}
size_t diff_doc__doc_index__get_packed_size
                     (const DiffDoc__DocIndex *message)
{
  assert(message->base.descriptor == &diff_doc__doc_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__doc_index__pack
                     (const DiffDoc__DocIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__doc_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__doc_index__pack_to_buffer
                     (const DiffDoc__DocIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__doc_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DocIndex *
       diff_doc__doc_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DocIndex *)
     protobuf_c_message_unpack (&diff_doc__doc_index__descriptor,
                                allocator, len, data);
}
void   diff_doc__doc_index__free_unpacked
                     (DiffDoc__DocIndex *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__doc_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__hunk_action__init
                     (DiffDoc__HunkAction         *message)
{
  static const DiffDoc__HunkAction init_value = DIFF_DOC__HUNK_ACTION__INIT;
  *message = init_value;
}
size_t diff_doc__hunk_action__get_packed_size
                     (const DiffDoc__HunkAction *message)
{
  assert(message->base.descriptor == &diff_doc__hunk_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__hunk_action__pack
                     (const DiffDoc__HunkAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__hunk_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__hunk_action__pack_to_buffer
                     (const DiffDoc__HunkAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__hunk_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__HunkAction *
       diff_doc__hunk_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__HunkAction *)
     protobuf_c_message_unpack (&diff_doc__hunk_action__descriptor,
                                allocator, len, data);
}
void   diff_doc__hunk_action__free_unpacked
                     (DiffDoc__HunkAction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__hunk_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__generic_value__init
                     (DiffDoc__GenericValue         *message)
{
  static const DiffDoc__GenericValue init_value = DIFF_DOC__GENERIC_VALUE__INIT;
  *message = init_value;
}
size_t diff_doc__generic_value__get_packed_size
                     (const DiffDoc__GenericValue *message)
{
  assert(message->base.descriptor == &diff_doc__generic_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__generic_value__pack
                     (const DiffDoc__GenericValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__generic_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__generic_value__pack_to_buffer
                     (const DiffDoc__GenericValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__generic_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__GenericValue *
       diff_doc__generic_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__GenericValue *)
     protobuf_c_message_unpack (&diff_doc__generic_value__descriptor,
                                allocator, len, data);
}
void   diff_doc__generic_value__free_unpacked
                     (DiffDoc__GenericValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__generic_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__generic_map__fields_entry__init
                     (DiffDoc__GenericMap__FieldsEntry         *message)
{
  static const DiffDoc__GenericMap__FieldsEntry init_value = DIFF_DOC__GENERIC_MAP__FIELDS_ENTRY__INIT;
  *message = init_value;
}
void   diff_doc__generic_map__init
                     (DiffDoc__GenericMap         *message)
{
  static const DiffDoc__GenericMap init_value = DIFF_DOC__GENERIC_MAP__INIT;
  *message = init_value;
}
size_t diff_doc__generic_map__get_packed_size
                     (const DiffDoc__GenericMap *message)
{
  assert(message->base.descriptor == &diff_doc__generic_map__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__generic_map__pack
                     (const DiffDoc__GenericMap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__generic_map__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__generic_map__pack_to_buffer
                     (const DiffDoc__GenericMap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__generic_map__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__GenericMap *
       diff_doc__generic_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__GenericMap *)
     protobuf_c_message_unpack (&diff_doc__generic_map__descriptor,
                                allocator, len, data);
}
void   diff_doc__generic_map__free_unpacked
                     (DiffDoc__GenericMap *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__generic_map__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__generic_array__init
                     (DiffDoc__GenericArray         *message)
{
  static const DiffDoc__GenericArray init_value = DIFF_DOC__GENERIC_ARRAY__INIT;
  *message = init_value;
}
size_t diff_doc__generic_array__get_packed_size
                     (const DiffDoc__GenericArray *message)
{
  assert(message->base.descriptor == &diff_doc__generic_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__generic_array__pack
                     (const DiffDoc__GenericArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__generic_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__generic_array__pack_to_buffer
                     (const DiffDoc__GenericArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__generic_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__GenericArray *
       diff_doc__generic_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__GenericArray *)
     protobuf_c_message_unpack (&diff_doc__generic_array__descriptor,
                                allocator, len, data);
}
void   diff_doc__generic_array__free_unpacked
                     (DiffDoc__GenericArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__generic_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__txt_mismatch__init
                     (DiffDoc__TxtMismatch         *message)
{
  static const DiffDoc__TxtMismatch init_value = DIFF_DOC__TXT_MISMATCH__INIT;
  *message = init_value;
}
size_t diff_doc__txt_mismatch__get_packed_size
                     (const DiffDoc__TxtMismatch *message)
{
  assert(message->base.descriptor == &diff_doc__txt_mismatch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__txt_mismatch__pack
                     (const DiffDoc__TxtMismatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__txt_mismatch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__txt_mismatch__pack_to_buffer
                     (const DiffDoc__TxtMismatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__txt_mismatch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__TxtMismatch *
       diff_doc__txt_mismatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__TxtMismatch *)
     protobuf_c_message_unpack (&diff_doc__txt_mismatch__descriptor,
                                allocator, len, data);
}
void   diff_doc__txt_mismatch__free_unpacked
                     (DiffDoc__TxtMismatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__txt_mismatch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__diff_op__init
                     (DiffDoc__DiffOp         *message)
{
  static const DiffDoc__DiffOp init_value = DIFF_DOC__DIFF_OP__INIT;
  *message = init_value;
}
size_t diff_doc__diff_op__get_packed_size
                     (const DiffDoc__DiffOp *message)
{
  assert(message->base.descriptor == &diff_doc__diff_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__diff_op__pack
                     (const DiffDoc__DiffOp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__diff_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__diff_op__pack_to_buffer
                     (const DiffDoc__DiffOp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__diff_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DiffOp *
       diff_doc__diff_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DiffOp *)
     protobuf_c_message_unpack (&diff_doc__diff_op__descriptor,
                                allocator, len, data);
}
void   diff_doc__diff_op__free_unpacked
                     (DiffDoc__DiffOp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__diff_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__diff_op_remove__init
                     (DiffDoc__DiffOpRemove         *message)
{
  static const DiffDoc__DiffOpRemove init_value = DIFF_DOC__DIFF_OP_REMOVE__INIT;
  *message = init_value;
}
size_t diff_doc__diff_op_remove__get_packed_size
                     (const DiffDoc__DiffOpRemove *message)
{
  assert(message->base.descriptor == &diff_doc__diff_op_remove__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__diff_op_remove__pack
                     (const DiffDoc__DiffOpRemove *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__diff_op_remove__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__diff_op_remove__pack_to_buffer
                     (const DiffDoc__DiffOpRemove *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__diff_op_remove__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DiffOpRemove *
       diff_doc__diff_op_remove__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DiffOpRemove *)
     protobuf_c_message_unpack (&diff_doc__diff_op_remove__descriptor,
                                allocator, len, data);
}
void   diff_doc__diff_op_remove__free_unpacked
                     (DiffDoc__DiffOpRemove *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__diff_op_remove__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__diff_op_insert__init
                     (DiffDoc__DiffOpInsert         *message)
{
  static const DiffDoc__DiffOpInsert init_value = DIFF_DOC__DIFF_OP_INSERT__INIT;
  *message = init_value;
}
size_t diff_doc__diff_op_insert__get_packed_size
                     (const DiffDoc__DiffOpInsert *message)
{
  assert(message->base.descriptor == &diff_doc__diff_op_insert__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__diff_op_insert__pack
                     (const DiffDoc__DiffOpInsert *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__diff_op_insert__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__diff_op_insert__pack_to_buffer
                     (const DiffDoc__DiffOpInsert *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__diff_op_insert__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DiffOpInsert *
       diff_doc__diff_op_insert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DiffOpInsert *)
     protobuf_c_message_unpack (&diff_doc__diff_op_insert__descriptor,
                                allocator, len, data);
}
void   diff_doc__diff_op_insert__free_unpacked
                     (DiffDoc__DiffOpInsert *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__diff_op_insert__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__diff_op_update__init
                     (DiffDoc__DiffOpUpdate         *message)
{
  static const DiffDoc__DiffOpUpdate init_value = DIFF_DOC__DIFF_OP_UPDATE__INIT;
  *message = init_value;
}
size_t diff_doc__diff_op_update__get_packed_size
                     (const DiffDoc__DiffOpUpdate *message)
{
  assert(message->base.descriptor == &diff_doc__diff_op_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__diff_op_update__pack
                     (const DiffDoc__DiffOpUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__diff_op_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__diff_op_update__pack_to_buffer
                     (const DiffDoc__DiffOpUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__diff_op_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DiffOpUpdate *
       diff_doc__diff_op_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DiffOpUpdate *)
     protobuf_c_message_unpack (&diff_doc__diff_op_update__descriptor,
                                allocator, len, data);
}
void   diff_doc__diff_op_update__free_unpacked
                     (DiffDoc__DiffOpUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__diff_op_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff_doc__diff_op_append__init
                     (DiffDoc__DiffOpAppend         *message)
{
  static const DiffDoc__DiffOpAppend init_value = DIFF_DOC__DIFF_OP_APPEND__INIT;
  *message = init_value;
}
size_t diff_doc__diff_op_append__get_packed_size
                     (const DiffDoc__DiffOpAppend *message)
{
  assert(message->base.descriptor == &diff_doc__diff_op_append__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff_doc__diff_op_append__pack
                     (const DiffDoc__DiffOpAppend *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff_doc__diff_op_append__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff_doc__diff_op_append__pack_to_buffer
                     (const DiffDoc__DiffOpAppend *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff_doc__diff_op_append__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DiffDoc__DiffOpAppend *
       diff_doc__diff_op_append__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DiffDoc__DiffOpAppend *)
     protobuf_c_message_unpack (&diff_doc__diff_op_append__descriptor,
                                allocator, len, data);
}
void   diff_doc__diff_op_append__free_unpacked
                     (DiffDoc__DiffOpAppend *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff_doc__diff_op_append__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor diff_doc__mismatches__field_descriptors[3] =
{
  {
    "patch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DiffDoc__Mismatches, kind_case),
    offsetof(DiffDoc__Mismatches, patch),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__Mismatches, kind_case),
    offsetof(DiffDoc__Mismatches, doc),
    &diff_doc__doc_mismatch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__Mismatches, kind_case),
    offsetof(DiffDoc__Mismatches, text),
    &diff_doc__txt_mismatch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__mismatches__field_indices_by_name[] = {
  1,   /* field[1] = doc */
  0,   /* field[0] = patch */
  2,   /* field[2] = text */
};
static const ProtobufCIntRange diff_doc__mismatches__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor diff_doc__mismatches__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.Mismatches",
  "Mismatches",
  "DiffDoc__Mismatches",
  "diff_doc",
  sizeof(DiffDoc__Mismatches),
  3,
  diff_doc__mismatches__field_descriptors,
  diff_doc__mismatches__field_indices_by_name,
  1,  diff_doc__mismatches__number_ranges,
  (ProtobufCMessageInit) diff_doc__mismatches__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__doc_mismatch__field_descriptors[1] =
{
  {
    "hunks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__DocMismatch, n_hunks),
    offsetof(DiffDoc__DocMismatch, hunks),
    &diff_doc__hunk__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__doc_mismatch__field_indices_by_name[] = {
  0,   /* field[0] = hunks */
};
static const ProtobufCIntRange diff_doc__doc_mismatch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor diff_doc__doc_mismatch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DocMismatch",
  "DocMismatch",
  "DiffDoc__DocMismatch",
  "diff_doc",
  sizeof(DiffDoc__DocMismatch),
  1,
  diff_doc__doc_mismatch__field_descriptors,
  diff_doc__doc_mismatch__field_indices_by_name,
  1,  diff_doc__doc_mismatch__number_ranges,
  (ProtobufCMessageInit) diff_doc__doc_mismatch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__hunk__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__Hunk, n_path),
    offsetof(DiffDoc__Hunk, path),
    &diff_doc__doc_index__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__Hunk, value),
    &diff_doc__hunk_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__hunk__field_indices_by_name[] = {
  0,   /* field[0] = path */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange diff_doc__hunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor diff_doc__hunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.Hunk",
  "Hunk",
  "DiffDoc__Hunk",
  "diff_doc",
  sizeof(DiffDoc__Hunk),
  2,
  diff_doc__hunk__field_descriptors,
  diff_doc__hunk__field_indices_by_name,
  1,  diff_doc__hunk__number_ranges,
  (ProtobufCMessageInit) diff_doc__hunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__doc_index__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DiffDoc__DocIndex, kind_case),
    offsetof(DiffDoc__DocIndex, name),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DiffDoc__DocIndex, kind_case),
    offsetof(DiffDoc__DocIndex, idx),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__doc_index__field_indices_by_name[] = {
  1,   /* field[1] = idx */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange diff_doc__doc_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor diff_doc__doc_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DocIndex",
  "DocIndex",
  "DiffDoc__DocIndex",
  "diff_doc",
  sizeof(DiffDoc__DocIndex),
  2,
  diff_doc__doc_index__field_descriptors,
  diff_doc__doc_index__field_indices_by_name,
  1,  diff_doc__doc_index__number_ranges,
  (ProtobufCMessageInit) diff_doc__doc_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__hunk_action__field_descriptors[6] =
{
  {
    "remove",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, remove),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, update),
    &diff_doc__generic_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_txt",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, update_txt),
    &diff_doc__txt_mismatch__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insert",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, insert),
    &diff_doc__generic_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "swap",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, swap),
    &diff_doc__doc_index__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clone",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__HunkAction, kind_case),
    offsetof(DiffDoc__HunkAction, clone),
    &diff_doc__doc_index__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__hunk_action__field_indices_by_name[] = {
  5,   /* field[5] = clone */
  3,   /* field[3] = insert */
  0,   /* field[0] = remove */
  4,   /* field[4] = swap */
  1,   /* field[1] = update */
  2,   /* field[2] = update_txt */
};
static const ProtobufCIntRange diff_doc__hunk_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor diff_doc__hunk_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.HunkAction",
  "HunkAction",
  "DiffDoc__HunkAction",
  "diff_doc",
  sizeof(DiffDoc__HunkAction),
  6,
  diff_doc__hunk_action__field_descriptors,
  diff_doc__hunk_action__field_indices_by_name,
  1,  diff_doc__hunk_action__number_ranges,
  (ProtobufCMessageInit) diff_doc__hunk_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__generic_value__field_descriptors[6] =
{
  {
    "numeric",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, numeric),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, map),
    &diff_doc__generic_map__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, array),
    &diff_doc__generic_array__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, boolean),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, string),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "null",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DiffDoc__GenericValue, kind_case),
    offsetof(DiffDoc__GenericValue, null),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__generic_value__field_indices_by_name[] = {
  2,   /* field[2] = array */
  3,   /* field[3] = boolean */
  1,   /* field[1] = map */
  5,   /* field[5] = null */
  0,   /* field[0] = numeric */
  4,   /* field[4] = string */
};
static const ProtobufCIntRange diff_doc__generic_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor diff_doc__generic_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.GenericValue",
  "GenericValue",
  "DiffDoc__GenericValue",
  "diff_doc",
  sizeof(DiffDoc__GenericValue),
  6,
  diff_doc__generic_value__field_descriptors,
  diff_doc__generic_value__field_indices_by_name,
  1,  diff_doc__generic_value__number_ranges,
  (ProtobufCMessageInit) diff_doc__generic_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__generic_map__fields_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__GenericMap__FieldsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__GenericMap__FieldsEntry, value),
    &diff_doc__generic_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__generic_map__fields_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange diff_doc__generic_map__fields_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor diff_doc__generic_map__fields_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.GenericMap.FieldsEntry",
  "FieldsEntry",
  "DiffDoc__GenericMap__FieldsEntry",
  "diff_doc",
  sizeof(DiffDoc__GenericMap__FieldsEntry),
  2,
  diff_doc__generic_map__fields_entry__field_descriptors,
  diff_doc__generic_map__fields_entry__field_indices_by_name,
  1,  diff_doc__generic_map__fields_entry__number_ranges,
  (ProtobufCMessageInit) diff_doc__generic_map__fields_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__generic_map__field_descriptors[1] =
{
  {
    "fields",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__GenericMap, n_fields),
    offsetof(DiffDoc__GenericMap, fields),
    &diff_doc__generic_map__fields_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__generic_map__field_indices_by_name[] = {
  0,   /* field[0] = fields */
};
static const ProtobufCIntRange diff_doc__generic_map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor diff_doc__generic_map__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.GenericMap",
  "GenericMap",
  "DiffDoc__GenericMap",
  "diff_doc",
  sizeof(DiffDoc__GenericMap),
  1,
  diff_doc__generic_map__field_descriptors,
  diff_doc__generic_map__field_indices_by_name,
  1,  diff_doc__generic_map__number_ranges,
  (ProtobufCMessageInit) diff_doc__generic_map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__generic_array__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__GenericArray, n_items),
    offsetof(DiffDoc__GenericArray, items),
    &diff_doc__generic_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__generic_array__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange diff_doc__generic_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor diff_doc__generic_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.GenericArray",
  "GenericArray",
  "DiffDoc__GenericArray",
  "diff_doc",
  sizeof(DiffDoc__GenericArray),
  1,
  diff_doc__generic_array__field_descriptors,
  diff_doc__generic_array__field_indices_by_name,
  1,  diff_doc__generic_array__number_ranges,
  (ProtobufCMessageInit) diff_doc__generic_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__txt_mismatch__field_descriptors[1] =
{
  {
    "ops",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__TxtMismatch, n_ops),
    offsetof(DiffDoc__TxtMismatch, ops),
    &diff_doc__diff_op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__txt_mismatch__field_indices_by_name[] = {
  0,   /* field[0] = ops */
};
static const ProtobufCIntRange diff_doc__txt_mismatch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor diff_doc__txt_mismatch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.TxtMismatch",
  "TxtMismatch",
  "DiffDoc__TxtMismatch",
  "diff_doc",
  sizeof(DiffDoc__TxtMismatch),
  1,
  diff_doc__txt_mismatch__field_descriptors,
  diff_doc__txt_mismatch__field_indices_by_name,
  1,  diff_doc__txt_mismatch__number_ranges,
  (ProtobufCMessageInit) diff_doc__txt_mismatch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__diff_op__field_descriptors[4] =
{
  {
    "remove",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__DiffOp, kind_case),
    offsetof(DiffDoc__DiffOp, remove),
    &diff_doc__diff_op_remove__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insert",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__DiffOp, kind_case),
    offsetof(DiffDoc__DiffOp, insert),
    &diff_doc__diff_op_insert__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__DiffOp, kind_case),
    offsetof(DiffDoc__DiffOp, update),
    &diff_doc__diff_op_update__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "append",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DiffDoc__DiffOp, kind_case),
    offsetof(DiffDoc__DiffOp, append),
    &diff_doc__diff_op_append__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__diff_op__field_indices_by_name[] = {
  3,   /* field[3] = append */
  1,   /* field[1] = insert */
  0,   /* field[0] = remove */
  2,   /* field[2] = update */
};
static const ProtobufCIntRange diff_doc__diff_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor diff_doc__diff_op__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DiffOp",
  "DiffOp",
  "DiffDoc__DiffOp",
  "diff_doc",
  sizeof(DiffDoc__DiffOp),
  4,
  diff_doc__diff_op__field_descriptors,
  diff_doc__diff_op__field_indices_by_name,
  1,  diff_doc__diff_op__number_ranges,
  (ProtobufCMessageInit) diff_doc__diff_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__diff_op_remove__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpRemove, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__diff_op_remove__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange diff_doc__diff_op_remove__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor diff_doc__diff_op_remove__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DiffOpRemove",
  "DiffOpRemove",
  "DiffDoc__DiffOpRemove",
  "diff_doc",
  sizeof(DiffDoc__DiffOpRemove),
  1,
  diff_doc__diff_op_remove__field_descriptors,
  diff_doc__diff_op_remove__field_indices_by_name,
  1,  diff_doc__diff_op_remove__number_ranges,
  (ProtobufCMessageInit) diff_doc__diff_op_remove__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__diff_op_insert__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpInsert, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpInsert, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__diff_op_insert__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange diff_doc__diff_op_insert__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor diff_doc__diff_op_insert__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DiffOpInsert",
  "DiffOpInsert",
  "DiffDoc__DiffOpInsert",
  "diff_doc",
  sizeof(DiffDoc__DiffOpInsert),
  2,
  diff_doc__diff_op_insert__field_descriptors,
  diff_doc__diff_op_insert__field_indices_by_name,
  1,  diff_doc__diff_op_insert__number_ranges,
  (ProtobufCMessageInit) diff_doc__diff_op_insert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__diff_op_update__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpUpdate, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpUpdate, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__diff_op_update__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange diff_doc__diff_op_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor diff_doc__diff_op_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DiffOpUpdate",
  "DiffOpUpdate",
  "DiffDoc__DiffOpUpdate",
  "diff_doc",
  sizeof(DiffDoc__DiffOpUpdate),
  2,
  diff_doc__diff_op_update__field_descriptors,
  diff_doc__diff_op_update__field_indices_by_name,
  1,  diff_doc__diff_op_update__number_ranges,
  (ProtobufCMessageInit) diff_doc__diff_op_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff_doc__diff_op_append__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpAppend, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpAppend, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DiffDoc__DiffOpAppend, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff_doc__diff_op_append__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = pos */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange diff_doc__diff_op_append__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor diff_doc__diff_op_append__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "diff_doc.DiffOpAppend",
  "DiffOpAppend",
  "DiffDoc__DiffOpAppend",
  "diff_doc",
  sizeof(DiffDoc__DiffOpAppend),
  3,
  diff_doc__diff_op_append__field_descriptors,
  diff_doc__diff_op_append__field_indices_by_name,
  1,  diff_doc__diff_op_append__number_ranges,
  (ProtobufCMessageInit) diff_doc__diff_op_append__init,
  NULL,NULL,NULL    /* reserved[123] */
};
